---
title: "dartDown"
subtitle: "Aesthetically pleasing DART departure times"
author: "<br>Luke McGuinness"
institute: "Dublin DataViz<br>17th September, 2025"
date: ""
output:
  xaringan::moon_reader:
    css: ["default", "my-theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      ratio: '16:9'
      highlightSpans: true
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

class: largest

# Why?

.em[Always] running late 🕐

--

Wanted to work with a .em['live'] data source

--

Interested in .em[functional-aesthetic] data viz - helping me .em[make decisions] or .em[take action], while also being .em[visually appealing]

<br>

---

class: largest

# Design Notes

Data from the .em[[Irish Rail API](https://api.irishrail.ie/realtime/)]

HTML/CSS/Javascript.em[*]

.emdart[DART colour palette]

.em[Query builder] page to create a personalized view

Additional code to enable .em[fullscreen on iOS]

.footer[*Drawing on by the [bartDown](https://github.com/powerlanguage/bartDown) project]


---

class: fullbleed

<iframe class="full-iframe" src="https://mcguinlu.github.io/dartDown/?refresh=10"></iframe>


---

class: fullbleed

<iframe class="full-iframe" src="https://mcguinlu.github.io/dartDown/about"></iframe>

---

class: largest

# Learnings #1 - 'Live' Data

First time working with 'live' data source via API

Two early quirks:
- `TrainType` value changed from `DART` -> `DART10` -> `DART` - .em[use fuzzy matching]
- Engineering works meant `Destination` variable was changeable - .em[limit to trains going to end of the line]

---

class: largest

# Learnings #2 - CORS

- Required to allow Javascript to access API

- Initially using a free CORS proxy service = .em[brittle/frustrating]

- Spun up personal CORS proxy, hosted on Vercel = .em[much better!]